version: '3'
services: 
  djangoapp:
    container_name: django-app
    build: .
    volumes:
      - .:/code
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    networks:
      - worksite_network
    depends_on:
      - mysql

  nginx:
    container_name: django-nginx
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - worksite_network
   
  mysql:
    container_name: django-mysql
    platform: linux/x86_64
    image: mysql
    restart: always
    env_file:
      - .env-mysql
    networks:
      - worksite_network
    volumes:
      - mysql_volume:/etc/mysql/conf.d
      - ./mysql:/docker-entrypoint-initdb.d
   
networks:
  worksite_network:
    driver: bridge

volumes:
  mysql_volume:
  static_volume:
  media_volume: