version: '3'
services: 
  djangoapp:
    container_name: django-app
    build: .
    volumes:
      - .:/code
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    networks:
      - worksite_network
    depends_on:
      - mysql

  nginx:
    container_name: django-nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - worksite_network
   
  mysql:
    container_name: django-mysql
    platform: linux/x86_64
    image: mysql
    restart: always
    env_file:
      - mysql.env
    networks:
      - worksite_network
    volumes:
      - mysql_volume:/etc/mysql/conf.d
   
networks:
  worksite_network:
    driver: bridge

volumes:
  mysql_volume:
  static_volume:
  media_volume: