version: '3'
services: 
  wms:
    build: .
    container_name: wms
    volumes:
      - .:/code
      - static_volume:/opt/services/wms/static
      - media_volume:/opt/services/wms/media
    networks:
      - worksite_network
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: wms-nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/opt/services/wms/static
      - media_volume:/opt/services/wms/media
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - wms
    networks:
      - worksite_network
   
  mysql:
    image: mysql
    platform: linux/x86_64
    container_name: wms-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - worksite_network
    volumes:
      - mysql_volume:/etc/mysql/conf.d
      - ./mysql:/docker-entrypoint-initdb.d
   
networks:
  worksite_network:
    driver: bridge

volumes:
  mysql_volume:
  static_volume:
  media_volume: